### ISSUE TITLE
Can't install on meteor

### ISSUE THREAD

**Issue by JoaoCardoso193** [Sarodus/svelte-quicksearch-bar#8]
Trying to use this package in a project built with Meteor.js and Svelte. For some reason, the install isn't going through, and I'm getting the following error message:

```
Unable to resolve some modules:

  "svelte-quicksearch-bar@latest" in /home/actualfood/Documents/AFDB/app/imports/ui/mainObjects/fields/relatedSources/Create.svelte (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save svelte-quicksearch-bar@latest
```

I've run `meteor npm install --save svelte-quicksearch-bar@latest` with no success.

I'm not sure what is causing this, I'm using other Svelte packages in this project with no issues. Any help would be greatly appreciated.

**Comment by Sarodus** [comment]
Hi @JoaoCardoso193 !

Not sure how meteor works but I was able to reproduce an error with a sample app. I could mount the component importing with
```
import QuickSearchBar from "svelte-quicksearch-bar/src/QuickSearchBar.svelte";
```

Seems that with meteor is not getting the right import path defined in the `package.json`
 that would be `"svelte": "src/index.js",`

You can use that import I said, but I'd like if you can provide me some sample of some working other svelte libraries that you're using in meteor, so I can see the diferences building the package

Thanks!
